---
title: "Advice on Statistical Methods for Bradford Hull's Research"
author: "Huashi Li (lihuashi1@arizona.edu), Alex Salce (asalce@arizona.edu), Taryn Laird (tarynl@arizona.edu)"
date: "2024-09-26"
output: 
  html_document:
    df_print: paged
    theme: cosmo
  pdf_document: default
header-includes:
- \renewcommand*\familydefault{\sfdefault} %% this picks a sans serif font
- \usepackage[T1]{fontenc}
---

## Executive Summary

Bradford Hull is a 5th year PhD Student in Molecular and Cellular Biology. He is currently researching lifespans of Caenorhabditis elegans worms and the effects of  different stressors for worms living in different media. Part of his research goal is to perform statistical analyses to determine whether any of these stressors have significant effects on the lifespans of the worms, both within media (compared to a control) and between media for the same stressors. 

By the time of our consultation, Bradford had already performed experiments and collected data for both agar and liquid media, using copper and DTT (dithiothreitol) as stressors. Due to some challenges unique to each media, he was not able to perform the same procedure to capture data for each media. 

Bradford was able to provide his data in Excel for our review. The agar media experiments were performed in a manner suitable for the framework of Kaplan-Meier methods for lifespan analysis, which he has already successfully performed using the `survival` package in $R$. However, his data collection for the liquid media experiments required a different procedure that we determined was not suitable for the Kaplan-Meier analysis framework, and the desired statistical analyses would require a different approach.

**Update with summary details of our reccomended approaches, and whether they will be able to accomplish all of his desired comparisons**

## Detailed Summary

### Background

Bradford is seeking statistical consultation to help him determine how to adequately approach a statistical analysis for data which he has already captured from several experiments. His research intent is to study the effects of different stressors on the lifespans of worms living in different media.

During our consultation, he was able to describe in detail the procedures that were carried out.  First, agar experimental units were made by adding $N=40$ worms to 9 total agar culture dishes. Stressors, copper and DTT (dithiothreitol), were each added to three of the cultures so that in total there were three of each stressor as well as 3 control cultures in agar media. The $N=40$ and three replicates were chosen based on a power analysis from within MCB, but no further details were provided.

Next, liquid experimental units were made by adding approximately $N \approx 5000$ worms to each of three separate liquid reservoirs. Each stressor was added to one reservoir so that there was one control reservoir and two reservoirs with respective stressors. 

It is important to note that all worms were originally drawn from the same population batch of eggs, and that all experimental units were prepared at the same time (same day).

Ultimately, Bradford's goals for analysis are the following (in his words, taken from a follow up email statement).

+ "...determine if the liquid data can be fit into a K-M curve (and therefore be able to use the log-rank test on it)"
+ "...determine if liquid copper and DTT are different from liquid control"
+ "determine if lifespan reductions for both copper and DTT from goal 2 are different from lifespan reductions in the agar data"

Our team agreed that our next steps would be the following.

+ Analyze whether the Kaplan-Meier (K-M) procedure is appropriate
  + Within media by stressor
  + Between media by analagous stressor
+ Determine what conditions need to be met for a valid K-M analysis, and if those conditions cannot be met, what approach do we recommend for analysis?

### Methods

The study began the day the experimental units were prepared and all worms were alive at the start time step. Every two days, all experimental units had data collected. However, the procedure for data collection was not the same between experimental units in agar media and units in liquid media.

#### Agar

At each timestep, each agar culture sample was able to be observed in its entirety, that is all of the original $N=40$ worms in each sample could be observed, and the number of dead worms were counted. In this sense, individual worms were tracked throughout each timestep of the study, which is an important condition for Kaplan-Meier lifespan analysis. Each experimental unit's data was recorded until all worms in their respective units were deceased.

#### Liquid

Due to challenges with measurement/observation of the worms in liquid media, the experimental procedure did not allow for the observation of the same worms. At each time step, a sample of approximately $150\text{mL}$ was drawn and placed in a clean apparatus where raw numbers of dead/alive worms could be recorded.

### Results

#### Agar

The procedure for agar media allowed for a straightforward Kaplan-Meier analysis of lifespan data for the desired within-media comparisons, using the `survival` package in R.

#### Liquid



#### Interpretation of Results


### Appendix


